"""Add index to active field for the Subscription model

Revision ID: 1fa23a128098
Revises: 664f59cd0e68
Create Date: 2025-09-03 02:44:59.385776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa23a128098'
down_revision = '664f59cd0e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index('ix_active', ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index('ix_active')

    # ### end Alembic commands ###
