"""Add UserType to User model

Revision ID: 664f59cd0e68
Revises: ed3c9d9595ab
Create Date: 2025-09-03 01:51:03.568626

"""
from alembic import op
import sqlalchemy as sa
from models.user import UserTypeEnum, UserType


# revision identifiers, used by Alembic.
revision = '664f59cd0e68'
down_revision = 'ed3c9d9595ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'user_type',
                UserTypeEnum(length=10),
                server_default=sa.text(f"'{UserType.REGULAR.value}'"),
                nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
