"""Allow only one Subscription per User

Revision ID: aee3e5052ef6
Revises: 1fa23a128098
Create Date: 2025-09-03 03:46:15.088275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee3e5052ef6'
down_revision = '1fa23a128098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'unique_user_per_subscription', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(
            'unique_user_per_subscription', type_='unique')

    # ### end Alembic commands ###
