"""Add initial models

Revision ID: db539ae5ff5d
Revises: 
Create Date: 2025-09-02 14:48:04.304632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db539ae5ff5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('plan_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('cost', sa.Float(), nullable=False),
                    sa.Column('months_duration', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=254), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=128), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=254), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=254), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('subscription',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('to_be_canceled', sa.Boolean(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('plan_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['plan_id'], ['subscription_plan.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('user')
    op.drop_table('subscription_plan')
    # ### end Alembic commands ###
