"""Update Subscription model to track payments

Revision ID: ed3c9d9595ab
Revises: c8402c557a7d
Create Date: 2025-09-02 20:15:41.404808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3c9d9595ab'
down_revision = 'c8402c557a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_end_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('payment_end_date')
        batch_op.drop_column('payment_start_date')

    # ### end Alembic commands ###
